[theme]
primaryColor = "#448aff"
backgroundColor = "#0a0e14"
secondaryBackgroundColor = "#131820"
textColor = "#c8d0e0"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
